# Exercise 2: Data preparation and exploration

In this notebook, we cover:

| Exercise part                         | Time (min) |
|---------------------------------------|------------|
| [Data structuring I](#structuring_1)  | 15         |
| [Data structuring II](#structuring_2) | 20         |
| [Data cleansing](#cleansing)          | 20         |
| [EDA: Clustering](#clustering)        | 25         |
| [Wrap-up](#wrap-up)                   | 10         |
| Overall                               | 90         |

<br>

> **Recommended workflow:**
>
> 1.  ✏️ **Think & plan first:** In the **PDF**, draft your answers and
>     outline the transformation steps before coding  
> 2.  💻 **Then code:** Implement your solution in the **Jupyter
>     Notebook**
>
> **The Jupyter Notebook is available in the Codespace (repository)
> here:**  
> <https://github.com/fs-ise/analytics-and-big-data-notebooks>
>
> For the *pandas* library, refer to [this cheat
> sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf).



# Part 1: Data structuring I <a id="structuring_1"></a>

We start with the `market_data_log.csv` dataset.

In [1]:
import pandas as pd
market_data_log_df = pd.read_csv("data/market_data_log.csv")
market_data_log_df.head()

<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">

<thead>

<tr class="header">

<th data-quarto-table-cell-role="th">

</th>

<th data-quarto-table-cell-role="th">

timestamp

</th>

<th data-quarto-table-cell-role="th">

logger_sys

</th>

<th data-quarto-table-cell-role="th">

Record

</th>

</tr>

</thead>

<tbody>

<tr class="odd">

<td data-quarto-table-cell-role="th">

0

</td>

<td>

2024-10-16 00:00:00

</td>

<td>

FIN-PIPE-V1

</td>

<td>

SAP-DE-Tech-2023Q1-MarketCap-1154.9B

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

1

</td>

<td>

2023-04-25 00:00:00

</td>

<td>

FIN-PIPE-V1

</td>

<td>

SAP-DE-Tech-2023Q1-Revenue-475.6B

</td>

</tr>

<tr class="odd">

<td data-quarto-table-cell-role="th">

2

</td>

<td>

2023-01-26 00:00:00

</td>

<td>

FIN-PIPE-V1

</td>

<td>

SAP-DE-Tech-2023Q1-EBITDA-146.7B

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

3

</td>

<td>

2023-10-09 00:00:00

</td>

<td>

FIN-PIPE-V1

</td>

<td>

SAP-DE-Tech-2023Q2-MarketCap-1816.0B

</td>

</tr>

<tr class="odd">

<td data-quarto-table-cell-role="th">

4

</td>

<td>

2023-09-08 00:00:00

</td>

<td>

FIN-PIPE-V1

</td>

<td>

SAP-DE-Tech-2023Q2-Revenue-82.2B

</td>

</tr>

</tbody>

</table>

### Tasks

1.  Identify:

    -   Values: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
    -   Observations: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
    -   Variables: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
    -   Units of observation: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

2.  Draft the **tidy structure** of the dataset:

    -   Fill in the column names and at least 3 example rows.

<table style="width:100%; border-collapse:collapse; font-family:Arial, sans-serif; color:#222;">

<thead>

<tr>

<th style="background:#f2f2f2; border:1px solid #ccc; padding:10px;">

 

</th>

<th style="background:#f2f2f2; border:1px solid #ccc; padding:10px;">

 

</th>

<th style="background:#f2f2f2; border:1px solid #ccc; padding:10px;">

 

</th>

<th style="background:#f2f2f2; border:1px solid #ccc; padding:10px;">

 

</th>

<th style="background:#f2f2f2; border:1px solid #ccc; padding:10px;">

 

</th>

<th style="background:#f2f2f2; border:1px solid #ccc; padding:10px;">

 

</th>

<th style="background:#f2f2f2; border:1px solid #ccc; padding:10px;">

 

</th>

<th style="background:#f2f2f2; border:1px solid #ccc; padding:10px;">

 

</th>

</tr>

</thead>

<tbody>

<tr>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

</tr>

<tr>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

</tr>

<tr>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

</tr>

<tr>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

</tr>

</tbody>

</table>

1.  Describe how the dataset should be transformed.

<br><br><br><br>

1.  **(Optional challenge)**: Implement the transformation in Python
    (pandas)

In [2]:
import pandas as pd

market_data_df = pd.read_csv("data/market_data_log.csv")

# Your solution (in Jupyter notebook)
# Note: you may need string operations

If you didn’t get to this part in class, try working through it at home.

> **Expectations in the exam**
>
> <br>
>
> <table style="border-collapse: collapse; width: 100%; font-family: Arial, sans-serif;">
>
> <thead>
>
> <tr style="background-color: #f2f2f2;">
>
> <th style="border: 1px solid #ccc; padding: 8px;">
>
> Grade
>
> </th>
>
> <th style="border: 1px solid #ccc; padding: 8px;">
>
> Expectations
>
> </th>
>
> </tr>
>
> </thead>
>
> <tbody>
>
> <tr>
>
> <td style="border: 1px solid #ccc; padding: 8px;">
>
> <strong>1 (Best)</strong>
>
> </td>
>
> <td style="border: 1px solid #ccc; padding: 8px;">
>
> <strong>Recommend</strong> how to fix the dataset using appropriate
> transformations, e.g., describe restructuring steps, select the
> correct method from examples, or provide pseudocode.
>
> </td>
>
> </tr>
>
> <tr>
>
> <td style="border: 1px solid #ccc; padding: 8px;">
>
> <strong>2</strong>
>
> </td>
>
> <td style="border: 1px solid #ccc; padding: 8px;">
>
> <strong>Evaluate</strong> and justify the decision using tidy data
> principles, e.g., “This is not tidy because column 2 contains two
> variables instead of one.”
>
> </td>
>
> </tr>
>
> <tr>
>
> <td style="border: 1px solid #ccc; padding: 8px;">
>
> <strong>3</strong>
>
> </td>
>
> <td style="border: 1px solid #ccc; padding: 8px;">
>
> <strong>Apply</strong> tidy data principles to evaluate a dataset
> (correctly identify whether it is tidy or not).
>
> </td>
>
> </tr>
>
> <tr>
>
> <td style="border: 1px solid #ccc; padding: 8px;">
>
> <strong>4 (Pass)</strong>
>
> </td>
>
> <td style="border: 1px solid #ccc; padding: 8px;">
>
> <strong>Understand</strong> and reproduce the principles of tidy data
> (e.g., each variable in a column, each observation in a row).
>
> </td>
>
> </tr>
>
> </tbody>
>
> </table>
>
> <p style="font-family: Arial, sans-serif; margin-top: 10px;">
>
> <strong>Note:</strong> Even for the best grade, you are not expected
> to write fully functional code from memory. Still, practicing with
> code will help you build a deeper conceptual understanding.
>
> </p>

------------------------------------------------------------------------



# Part 2: Data structuring II <a id="structuring_2"></a>

Dataset `sales_data_channels_full_year.csv`

In [4]:
import pandas as pd
sales_data_df = pd.read_csv("data/sales_data_channels_full_year.csv")
sales_data_df.head()

<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">

<thead>

<tr class="header">

<th data-quarto-table-cell-role="th">

</th>

<th data-quarto-table-cell-role="th">

Customer_ID

</th>

<th data-quarto-table-cell-role="th">

Region

</th>

<th data-quarto-table-cell-role="th">

Jan_Online

</th>

<th data-quarto-table-cell-role="th">

Jan_Store

</th>

<th data-quarto-table-cell-role="th">

Feb_Online

</th>

<th data-quarto-table-cell-role="th">

Feb_Store

</th>

<th data-quarto-table-cell-role="th">

Mar_Online

</th>

<th data-quarto-table-cell-role="th">

Mar_Store

</th>

<th data-quarto-table-cell-role="th">

Apr_Online

</th>

<th data-quarto-table-cell-role="th">

Apr_Store

</th>

<th data-quarto-table-cell-role="th">

…

</th>

<th data-quarto-table-cell-role="th">

Aug_Online

</th>

<th data-quarto-table-cell-role="th">

Aug_Store

</th>

<th data-quarto-table-cell-role="th">

Sep_Online

</th>

<th data-quarto-table-cell-role="th">

Sep_Store

</th>

<th data-quarto-table-cell-role="th">

Oct_Online

</th>

<th data-quarto-table-cell-role="th">

Oct_Store

</th>

<th data-quarto-table-cell-role="th">

Nov_Online

</th>

<th data-quarto-table-cell-role="th">

Nov_Store

</th>

<th data-quarto-table-cell-role="th">

Dec_Online

</th>

<th data-quarto-table-cell-role="th">

Dec_Store

</th>

</tr>

</thead>

<tbody>

<tr class="odd">

<td data-quarto-table-cell-role="th">

0

</td>

<td>

ACC-E0IFD0

</td>

<td>

APAC

</td>

<td>

215

</td>

<td>

201

</td>

<td>

240

</td>

<td>

73

</td>

<td>

80

</td>

<td>

184

</td>

<td>

224

</td>

<td>

240

</td>

<td>

…

</td>

<td>

182

</td>

<td>

180

</td>

<td>

108

</td>

<td>

154

</td>

<td>

278

</td>

<td>

76

</td>

<td>

85

</td>

<td>

211

</td>

<td>

148

</td>

<td>

132

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

1

</td>

<td>

ACC-DPBHSA

</td>

<td>

EU

</td>

<td>

315

</td>

<td>

108

</td>

<td>

251

</td>

<td>

163

</td>

<td>

133

</td>

<td>

245

</td>

<td>

170

</td>

<td>

194

</td>

<td>

…

</td>

<td>

300

</td>

<td>

157

</td>

<td>

289

</td>

<td>

233

</td>

<td>

173

</td>

<td>

121

</td>

<td>

172

</td>

<td>

213

</td>

<td>

260

</td>

<td>

158

</td>

</tr>

<tr class="odd">

<td data-quarto-table-cell-role="th">

2

</td>

<td>

CUST-ZZPQK5

</td>

<td>

APAC

</td>

<td>

142

</td>

<td>

167

</td>

<td>

195

</td>

<td>

81

</td>

<td>

175

</td>

<td>

107

</td>

<td>

296

</td>

<td>

210

</td>

<td>

…

</td>

<td>

101

</td>

<td>

221

</td>

<td>

141

</td>

<td>

116

</td>

<td>

142

</td>

<td>

109

</td>

<td>

182

</td>

<td>

55

</td>

<td>

258

</td>

<td>

124

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

3

</td>

<td>

CUST-ZMF8MD

</td>

<td>

APAC

</td>

<td>

218

</td>

<td>

209

</td>

<td>

154

</td>

<td>

224

</td>

<td>

205

</td>

<td>

163

</td>

<td>

124

</td>

<td>

206

</td>

<td>

…

</td>

<td>

83

</td>

<td>

228

</td>

<td>

264

</td>

<td>

172

</td>

<td>

235

</td>

<td>

223

</td>

<td>

239

</td>

<td>

88

</td>

<td>

285

</td>

<td>

178

</td>

</tr>

<tr class="odd">

<td data-quarto-table-cell-role="th">

4

</td>

<td>

CUST-MMJBQE

</td>

<td>

EU

</td>

<td>

180

</td>

<td>

145

</td>

<td>

212

</td>

<td>

135

</td>

<td>

217

</td>

<td>

124

</td>

<td>

231

</td>

<td>

190

</td>

<td>

…

</td>

<td>

253

</td>

<td>

151

</td>

<td>

115

</td>

<td>

78

</td>

<td>

159

</td>

<td>

194

</td>

<td>

140

</td>

<td>

219

</td>

<td>

111

</td>

<td>

137

</td>

</tr>

</tbody>

</table>

<p>

5 rows × 26 columns

</p>

### Tasks

1.  Identify:

    -   Values: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
    -   Observations: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
    -   Variables: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
    -   Units of observation: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

2.  Draft the **tidy structure** of the dataset:

<table style="width:100%; border-collapse:collapse; font-family:Arial, sans-serif; color:#222;">

<thead>

<tr>

<th style="background:#f2f2f2; border:1px solid #ccc; padding:10px;">

 

</th>

<th style="background:#f2f2f2; border:1px solid #ccc; padding:10px;">

 

</th>

<th style="background:#f2f2f2; border:1px solid #ccc; padding:10px;">

 

</th>

<th style="background:#f2f2f2; border:1px solid #ccc; padding:10px;">

 

</th>

<th style="background:#f2f2f2; border:1px solid #ccc; padding:10px;">

 

</th>

</tr>

</thead>

<tbody>

<tr>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

</tr>

<tr>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

</tr>

<tr>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

</tr>

<tr>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

<td contenteditable="true" style="border:1px solid #ccc; padding:10px;">

 

</td>

</tr>

</tbody>

</table>

1.  Describe how the dataset should be transformed.

<br><br><br>

1.  **(Optional challenge)**: Implement the transformation in Python
    (pandas)

In [5]:
import pandas as pd

market_data_df = pd.read_csv("data/market_data_log.csv")

# Your solution (in Jupyter notebook)

In addition to the transformation, you may need string operations

------------------------------------------------------------------------



# Part 3: Data cleansing <a id="cleansing"></a>

Dataset `messy_customer_data.csv`

In [7]:
import pandas as pd
customers_df = pd.read_csv("data/messy_customer_data.csv")
customers_df.head()

<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">

<thead>

<tr class="header">

<th data-quarto-table-cell-role="th">

</th>

<th data-quarto-table-cell-role="th">

customer_id

</th>

<th data-quarto-table-cell-role="th">

date_of_birth

</th>

<th data-quarto-table-cell-role="th">

income

</th>

<th data-quarto-table-cell-role="th">

gender

</th>

<th data-quarto-table-cell-role="th">

signup_date

</th>

<th data-quarto-table-cell-role="th">

country

</th>

</tr>

</thead>

<tbody>

<tr class="odd">

<td data-quarto-table-cell-role="th">

0

</td>

<td>

CUST_00000001809

</td>

<td>

1980-04-09

</td>

<td>

4896 USD

</td>

<td>

M

</td>

<td>

2026-12-14

</td>

<td>

USA

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

1

</td>

<td>

CUST_00000000695

</td>

<td>

1945-08-02

</td>

<td>

7029

</td>

<td>

F

</td>

<td>

2023-11-26

</td>

<td>

BR

</td>

</tr>

<tr class="odd">

<td data-quarto-table-cell-role="th">

2

</td>

<td>

CUST_00000000907

</td>

<td>

1971-07-25

</td>

<td>

6432

</td>

<td>

F

</td>

<td>

2024-06-25

</td>

<td>

Austria

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

3

</td>

<td>

CUST_00000000545

</td>

<td>

2000-03-01

</td>

<td>

6107

</td>

<td>

M

</td>

<td>

2023-06-29

</td>

<td>

JP

</td>

</tr>

<tr class="odd">

<td data-quarto-table-cell-role="th">

4

</td>

<td>

CUST_00000001848

</td>

<td>

1943-09-06

</td>

<td>

7655

</td>

<td>

F

</td>

<td>

2027-01-22

</td>

<td>

Italy

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

5

</td>

<td>

CUST_00000001567

</td>

<td>

1980-09-14

</td>

<td>

2244

</td>

<td>

F

</td>

<td>

2026-04-16

</td>

<td>

CH

</td>

</tr>

<tr class="odd">

<td data-quarto-table-cell-role="th">

6

</td>

<td>

CUST_00000001573

</td>

<td>

1950-04-07

</td>

<td>

3262

</td>

<td>

F

</td>

<td>

2026-04-22

</td>

<td>

India

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

7

</td>

<td>

CUST_00000000945

</td>

<td>

1989-08-23

</td>

<td>

3976

</td>

<td>

M

</td>

<td>

2024-08-02

</td>

<td>

BR

</td>

</tr>

<tr class="odd">

<td data-quarto-table-cell-role="th">

8

</td>

<td>

CUST_00000000819

</td>

<td>

1946-03-09

</td>

<td>

3077 USD

</td>

<td>

F

</td>

<td>

2024-03-29

</td>

<td>

NL

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

9

</td>

<td>

CUST_00000000830

</td>

<td>

1981-03-30

</td>

<td>

NaN

</td>

<td>

M

</td>

<td>

2024-04-09

</td>

<td>

BR

</td>

</tr>

<tr class="odd">

<td data-quarto-table-cell-role="th">

10

</td>

<td>

CUST_00000001531

</td>

<td>

1995-03-08

</td>

<td>

4667

</td>

<td>

F

</td>

<td>

2026-03-11

</td>

<td>

DE

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

11

</td>

<td>

CUST_00000000979

</td>

<td>

1990-01-24

</td>

<td>

NaN

</td>

<td>

F

</td>

<td>

2024-09-05

</td>

<td>

Switzerland

</td>

</tr>

<tr class="odd">

<td data-quarto-table-cell-role="th">

12

</td>

<td>

CUST_00000001576

</td>

<td>

1989-06-18

</td>

<td>

2920

</td>

<td>

F

</td>

<td>

2026-04-25

</td>

<td>

Brazil

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

13

</td>

<td>

CUST_00000000786

</td>

<td>

1994-06-24

</td>

<td>

6613

</td>

<td>

F

</td>

<td>

2024-02-25

</td>

<td>

IT

</td>

</tr>

<tr class="odd">

<td data-quarto-table-cell-role="th">

14

</td>

<td>

CUST_00000000071

</td>

<td>

1960-11-19

</td>

<td>

4613

</td>

<td>

F

</td>

<td>

2022-03-12

</td>

<td>

FR

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

15

</td>

<td>

CUST_00000001007

</td>

<td>

1989-07-09

</td>

<td>

4551

</td>

<td>

F

</td>

<td>

2024-10-03

</td>

<td>

BR

</td>

</tr>

<tr class="odd">

<td data-quarto-table-cell-role="th">

16

</td>

<td>

CUST_00000000189

</td>

<td>

1969-01-29

</td>

<td>

6779

</td>

<td>

M

</td>

<td>

2022-07-08

</td>

<td>

China

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

17

</td>

<td>

CUST_00000001670

</td>

<td>

1987-08-04

</td>

<td>

7295

</td>

<td>

M

</td>

<td>

2026-07-28

</td>

<td>

Munch

</td>

</tr>

<tr class="odd">

<td data-quarto-table-cell-role="th">

18

</td>

<td>

CUST_00000001270

</td>

<td>

1969-02-06

</td>

<td>

4717

</td>

<td>

F

</td>

<td>

2025-06-23

</td>

<td>

USA

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

19

</td>

<td>

CUST_00000001305

</td>

<td>

1989-01-13

</td>

<td>

7954

</td>

<td>

F

</td>

<td>

2025-07-28

</td>

<td>

ES

</td>

</tr>

</tbody>

</table>



## Tasks

In this part, move from **detecting problems** to **making the dataset
analysis-ready**. The goal is not only to spot errors, but also to
document a reproducible cleaning strategy.

### 1. Identify scales of variables

-   What type of scale is each variable? Run the following and assign
    `nominal`, `ordinal`, `interval`, or `ratio`.

In [8]:
customer_df = pd.read_csv("data/messy_customer_data.csv")
customer_df.info()

-   What type of scale should each variable be? Assign `nominal`,
    `ordinal`, `interval`, or `ratio`.

    -   customer_id: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
    -   date_of_birth: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
    -   income: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
    -   gender: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
    -   signup_date: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
    -   country: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_



### 2. Analyze data quality

Examine the dataset `data/messy_customer_data.csv` and run the
following:

In [9]:
customer_df.describe()

-   Summarize all data quality issues you observe (open the
    [data/messy_customer_data.csv](data/messy_customer_data.csv)).

<br><br><br><br><br><br><br>



### 3. Propose data preparation steps

-   For each data quality issue, suggest how you would address it.

<br><br><br><br><br><br><br>

------------------------------------------------------------------------

### 4. *(Optional challenge)* Implement in Python (pandas)

-   Implement the data preparation steps in Python.
-   Run the code after each step and inspect the results.

In [10]:
# Your solution (in Jupyter notebook)

Note: Check how the `customer_df` changes after each preparation step!

------------------------------------------------------------------------



# Part 4: EDA: Clustering <a id="clustering"></a>

Now that the data is structured and cleaned, we explore whether
companies group into similar patterns. Clustering helps us move from
preparation to insight generation: instead of looking at firms one by
one, we ask whether there are recurring profiles in the data.

Dataset: `firm_data.csv`

In [13]:
import pandas as pd
firm_data_df = pd.read_csv("data/firm_data.csv")
firm_data_df.head()

<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">

<thead>

<tr class="header">

<th data-quarto-table-cell-role="th">

</th>

<th data-quarto-table-cell-role="th">

company_id

</th>

<th data-quarto-table-cell-role="th">

sector

</th>

<th data-quarto-table-cell-role="th">

revenue

</th>

<th data-quarto-table-cell-role="th">

profit_margin

</th>

<th data-quarto-table-cell-role="th">

growth_rate

</th>

<th data-quarto-table-cell-role="th">

debt_ratio

</th>

<th data-quarto-table-cell-role="th">

market_cap

</th>

<th data-quarto-table-cell-role="th">

rd_intensity

</th>

</tr>

</thead>

<tbody>

<tr class="odd">

<td data-quarto-table-cell-role="th">

0

</td>

<td>

FIRM-0095

</td>

<td>

Healthcare

</td>

<td>

2117.569743

</td>

<td>

13.382162

</td>

<td>

6.053507

</td>

<td>

0.555974

</td>

<td>

12426.889897

</td>

<td>

3.308879

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

1

</td>

<td>

FIRM-0015

</td>

<td>

Healthcare

</td>

<td>

457.538045

</td>

<td>

10.139487

</td>

<td>

21.504950

</td>

<td>

0.350252

</td>

<td>

5779.074618

</td>

<td>

8.710809

</td>

</tr>

<tr class="odd">

<td data-quarto-table-cell-role="th">

2

</td>

<td>

FIRM-0030

</td>

<td>

Industry

</td>

<td>

463.847307

</td>

<td>

4.131422

</td>

<td>

13.237034

</td>

<td>

0.356084

</td>

<td>

4451.965515

</td>

<td>

15.719744

</td>

</tr>

<tr class="even">

<td data-quarto-table-cell-role="th">

3

</td>

<td>

FIRM-0158

</td>

<td>

Finance

</td>

<td>

347.980562

</td>

<td>

9.573304

</td>

<td>

16.117482

</td>

<td>

0.472141

</td>

<td>

3256.609038

</td>

<td>

31.989645

</td>

</tr>

<tr class="odd">

<td data-quarto-table-cell-role="th">

4

</td>

<td>

FIRM-0128

</td>

<td>

Tech

</td>

<td>

804.239654

</td>

<td>

0.165357

</td>

<td>

-3.346796

</td>

<td>

0.761088

</td>

<td>

1825.004761

</td>

<td>

2.082579

</td>

</tr>

</tbody>

</table>

## Tasks

### 1. Prepare the data for clustering

We decide to use `profit_margin` and `rd_intensity` to cluster firms. In
a first step, create a dataframe `X` consisting of values for these two
variables:

In [14]:
import pandas as pd

df_firm_data = pd.read_csv("data/firm_data.csv")

# Your solution (in Jupyter notebook)

# Print X at the end

Before clustering, do a quick exploratory check so you know what kind of
patterns you are looking for.

In [15]:
X.describe()

In [16]:
df_firm_data[["profit_margin", "rd_intensity"]].hist(figsize=(6, 3))

Considering that k-means is sensitive to different measurement scale, we
need to standardize the values. This ensures that they have
approximately equal influence on the clusters.

Run the following code and observe how the scale of both variables
changes:

In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)
X

Before running a clustering algorithm, lets’s view the data in a
scatterplot:

In [18]:
import matplotlib.pyplot as plt

plt.scatter(X[:, 0], X[:, 1], s=10)
plt.title("Raw data (no clustering)")
plt.show()

How many clusters would you expect? Briefly justify your answer based on
the plot.

<br>

### 2. Apply K-Means clustering

-   Next, run the k-means clustering algorithm for different values of
    `k`.

In [19]:
from sklearn.cluster import KMeans

# Your solution (in Jupyter notebook)
# Note: consider the names of variables and objects used in the rest of the code

# Run the whole code cell to fit KMeans and plot it
plt.figure(figsize=(3.6, 2.8))
plt.scatter(X[:, 0], X[:, 1], c=labels, s=10)
plt.scatter(
    kmeans.cluster_centers_[:, 0],
    kmeans.cluster_centers_[:, 1],
    c='red', marker='x', s=60, linewidth=2
)
plt.title(f"k={k}", fontsize=10)
plt.xticks([])
plt.yticks([])
plt.tight_layout()
plt.show()

-   Try different values of K (e.g., 2–10). Which number of clusters
    seems appropriate?



### 3. Add cluster labels to the dataset

-   Assign the cluster labels returned by the k-means algorithm to the
    original dataframe (`df_firm_data`).

In [20]:
# Your solution (in Jupyter notebook)

------------------------------------------------------------------------

### 4. Create grouped boxplots

-   Generate a boxplot, grouped according to the clusters, to compare
    differences in `revenue`.
-   Try to complete the task relying only on the [pandas documentation
    for
    boxplots](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.boxplot.html).

In [21]:
import matplotlib.pyplot as plt

# Your solution (in Jupyter notebook)

------------------------------------------------------------------------



## Wrap-up <a id="wrap-up"></a>

🎉🎈 You have completed the notebook - good work! 🎈🎉

In this notebook, we have learned to

-   Structure data in a tidy format
-   Prepare and explore datasets
-   Apply clustering methods

> **Stop the Codespace**
>
> Remember to <b>stop</b> your Codespace
> [here](https://github.com/codespaces).

> **Session 2 survey**
>
> Before you wrap up, please complete the Session 2 survey here:
> <a href="https://forms.gle/XfRmmVbf1yaBwrky9"
> target="_blank">https://forms.gle/XfRmmVbf1yaBwrky9</a>. Thank you 🙏